
import type { Product } from './types';

// Datos de ejemplo para productos de bienestar.
// En una aplicación real, estos datos vendrían de una base de datos como Firestore.
export const wellnessProducts: Product[] = [
  {
    id: 'prod-001',
    name: 'Aceite Esencial de Lavanda',
    category: 'Aromaterapia',
    description: 'Aceite 100% puro para relajación y sueño profundo. Ideal para difusores o masajes.',
    price: 45000,
    image: 'https://picsum.photos/seed/lavender-oil/400/300',
    rating: 4.9,
    reviewCount: 150,
    inStock: true,
    aiHint: 'lavender oil',
    createdAt: '2023-11-01T10:00:00Z',
  },
  {
    id: 'prod-002',
    name: 'Vela Aromática de Sándalo',
    category: 'Aromaterapia',
    description: 'Crea un ambiente de paz y meditación con esta vela de cera de soja y aroma amaderado.',
    price: 75000,
    image: 'https://picsum.photos/seed/candle/400/300',
    rating: 4.8,
    reviewCount: 95,
    inStock: true,
    aiHint: 'scented candle',
    createdAt: '2023-11-02T11:00:00Z',
  },
  {
    id: 'prod-003',
    name: 'Kit de Masaje con Piedras Calientes',
    category: 'Accesorios',
    description: 'Set profesional de piedras de basalto para masajes terapéuticos y relajantes en casa.',
    price: 320000,
    image: 'https://picsum.photos/seed/hot-stones/400/300',
    rating: 4.7,
    reviewCount: 48,
    inStock: false,
    aiHint: 'hot stones',
    createdAt: '2023-11-03T12:00:00Z',
  },
  {
    id: 'prod-004',
    name: 'Sérum Facial con Vitamina C',
    category: 'Cuidado Facial',
    description: 'Potente antioxidante que ilumina, reafirma y protege tu piel del envejecimiento prematuro.',
    price: 150000,
    image: 'https://picsum.photos/seed/serum/400/300',
    rating: 4.9,
    reviewCount: 210,
    inStock: true,
    aiHint: 'facial serum',
    createdAt: '2023-11-04T13:00:00Z',
  },
   {
    id: 'prod-005',
    name: 'Té Matcha Orgánico Ceremonial',
    category: 'Nutrición',
    description: 'Té verde en polvo de la más alta calidad, rico en antioxidantes para energía y concentración.',
    price: 98000,
    image: 'https://picsum.photos/seed/matcha/400/300',
    rating: 4.8,
    reviewCount: 132,
    inStock: true,
    aiHint: 'matcha tea',
    createdAt: '2023-11-05T14:00:00Z',
  },
  {
    id: 'prod-006',
    name: 'Esterilla de Yoga Ecológica',
    category: 'Yoga y Meditación',
    description: 'Fabricada con corcho y caucho natural, antideslizante y amigable con el medio ambiente.',
    price: 280000,
    image: 'https://picsum.photos/seed/yoga-mat/400/300',
    rating: 4.9,
    reviewCount: 88,
    inStock: true,
    aiHint: 'yoga mat',
    createdAt: '2023-11-06T15:00:00Z',
  },
];
