
import type { WellnessService } from './types';

// Datos de ejemplo para servicios de bienestar.
// En una aplicación real, estos datos vendrían de una base de datos como Firestore.
export const wellnessServices: WellnessService[] = [
  {
    id: 'srv-001',
    name: 'Masaje Relajante Profundo',
    category: 'Masajes',
    description: 'Una experiencia de masaje diseñada para liberar la tensión muscular crónica y promover una relajación profunda y duradera.',
    price: 180000,
    image: 'https://picsum.photos/seed/massage/400/300',
    rating: 4.8,
    reviewCount: 75,
    duration: 60,
    aiHint: 'relaxing massage',
    createdAt: '2023-10-26T10:00:00Z',
  },
  {
    id: 'srv-002',
    name: 'Clase de Yoga Vinyasa',
    category: 'Yoga y Meditación',
    description: 'Fluye a través de posturas dinámicas sincronizadas con la respiración para mejorar la flexibilidad, fuerza y claridad mental.',
    price: 55000,
    image: 'https://picsum.photos/seed/yoga/400/300',
    rating: 4.9,
    reviewCount: 120,
    duration: 75,
    aiHint: 'yoga class',
    createdAt: '2023-10-25T11:00:00Z',
  },
  {
    id: 'srv-003',
    name: 'Facial de Hidratación Intensiva',
    category: 'Cuidado Facial',
    description: 'Un tratamiento facial que utiliza productos de alta gama para restaurar la hidratación, elasticidad y luminosidad de la piel.',
    price: 250000,
    image: 'https://picsum.photos/seed/facial/400/300',
    rating: 4.7,
    reviewCount: 90,
    duration: 50,
    aiHint: 'facial treatment',
    createdAt: '2023-10-24T14:30:00Z',
  },
  {
    id: 'srv-004',
    name: 'Sesión de Acupuntura',
    category: 'Terapias Alternativas',
    description: 'Terapia tradicional china para equilibrar el flujo de energía (Qi) y aliviar diversas dolencias físicas y emocionales.',
    price: 150000,
    image: 'https://picsum.photos/seed/acupuncture/400/300',
    rating: 4.9,
    reviewCount: 65,
    duration: 45,
    aiHint: 'acupuncture session',
    createdAt: '2023-10-23T16:00:00Z',
  },
  {
    id: 'srv-005',
    name: 'Manicura y Pedicura Spa',
    category: 'Cuidado de Manos y Pies',
    description: 'Un tratamiento de lujo que incluye exfoliación, mascarilla hidratante y un masaje relajante para manos y pies.',
    price: 95000,
    image: 'https://picsum.photos/seed/manicure/400/300',
    rating: 4.6,
    reviewCount: 210,
    duration: 90,
    aiHint: 'spa manicure',
    createdAt: '2023-10-22T12:00:00Z',
  },
  {
    id: 'srv-006',
    name: 'Consulta de Nutrición Holística',
    category: 'Nutrición',
    description: 'Recibe un plan de alimentación personalizado y consejos para mejorar tu bienestar general a través de la comida.',
    price: 300000,
    image: 'https://picsum.photos/seed/nutrition/400/300',
    rating: 5.0,
    reviewCount: 45,
    duration: 60,
    aiHint: 'nutrition consultation',
    createdAt: '2023-10-21T09:00:00Z',
  },
];
